set(DDS_ROOT "C:/Program Files/rti_connext_dds-7.5.0")

set(DDS_INCLUDE_DIRS
    ${DDS_ROOT}/include
    ${DDS_ROOT}/include/ndds
    ${DDS_ROOT}/lib/x64Win64VS2017
)

set(DDS_LIBRARY_DIRS
    ${DDS_ROOT}/lib/x64Win64VS2017
)

set(DDS_LIBRARIES
    ${DDS_LIBRARY_DIRS}/rtixml2zd.lib
    ${DDS_LIBRARY_DIRS}/lua.lib
    ${DDS_LIBRARY_DIRS}/luad.lib
    ${DDS_LIBRARY_DIRS}/luaz.lib
    ${DDS_LIBRARY_DIRS}/luazd.lib
    ${DDS_LIBRARY_DIRS}/nddsc.lib
    ${DDS_LIBRARY_DIRS}/nddscd.lib
    ${DDS_LIBRARY_DIRS}/nddscore.lib
    ${DDS_LIBRARY_DIRS}/nddscored.lib
    ${DDS_LIBRARY_DIRS}/nddscorez.lib
    ${DDS_LIBRARY_DIRS}/nddscorezd.lib
    ${DDS_LIBRARY_DIRS}/nddscpp.lib
    ${DDS_LIBRARY_DIRS}/nddscpp2.lib
    ${DDS_LIBRARY_DIRS}/nddscpp2d.lib
    ${DDS_LIBRARY_DIRS}/nddscpp2z.lib
    ${DDS_LIBRARY_DIRS}/nddscpp2zd.lib
    ${DDS_LIBRARY_DIRS}/nddscppd.lib
    ${DDS_LIBRARY_DIRS}/nddscppz.lib
    ${DDS_LIBRARY_DIRS}/nddscppzd.lib
    ${DDS_LIBRARY_DIRS}/nddsctesthelpers.lib
    ${DDS_LIBRARY_DIRS}/nddsctesthelpersd.lib
    ${DDS_LIBRARY_DIRS}/nddsctesthelpersz.lib
    ${DDS_LIBRARY_DIRS}/nddsctesthelperszd.lib
    ${DDS_LIBRARY_DIRS}/nddscz.lib
    ${DDS_LIBRARY_DIRS}/nddsczd.lib
    ${DDS_LIBRARY_DIRS}/nddsjava.lib
    ${DDS_LIBRARY_DIRS}/nddsjavad.lib
    ${DDS_LIBRARY_DIRS}/nddslightweightsecurity.lib
    ${DDS_LIBRARY_DIRS}/nddslightweightsecurityd.lib
    ${DDS_LIBRARY_DIRS}/nddslightweightsecurityz.lib
    ${DDS_LIBRARY_DIRS}/nddslightweightsecurityzd.lib
    ${DDS_LIBRARY_DIRS}/nddsmetp.lib
    ${DDS_LIBRARY_DIRS}/nddsmetpd.lib
    ${DDS_LIBRARY_DIRS}/nddsmetpz.lib
    ${DDS_LIBRARY_DIRS}/nddsmetpzd.lib
    ${DDS_LIBRARY_DIRS}/nddssecurity.lib
    ${DDS_LIBRARY_DIRS}/nddssecurityd.lib
    ${DDS_LIBRARY_DIRS}/nddssecurityz.lib
    ${DDS_LIBRARY_DIRS}/nddssecurityzd.lib
    ${DDS_LIBRARY_DIRS}/nddstransporttcp.lib
    ${DDS_LIBRARY_DIRS}/nddstransporttcpd.lib
    ${DDS_LIBRARY_DIRS}/nddstransporttcpz.lib
    ${DDS_LIBRARY_DIRS}/nddstransporttcpzd.lib
    ${DDS_LIBRARY_DIRS}/rtiapputilsc.lib
    ${DDS_LIBRARY_DIRS}/rtiapputilscd.lib
    ${DDS_LIBRARY_DIRS}/rtiapputilscz.lib
    ${DDS_LIBRARY_DIRS}/rtiapputilsczd.lib
    ${DDS_LIBRARY_DIRS}/rticlouddiscoveryservice.lib
    ${DDS_LIBRARY_DIRS}/rticlouddiscoveryserviced.lib
    ${DDS_LIBRARY_DIRS}/rticlouddiscoveryservicez.lib
    ${DDS_LIBRARY_DIRS}/rticlouddiscoveryservicezd.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgc.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcd.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcpp.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcpp2.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcpp2d.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcpp2z.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcpp2zd.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcppd.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcppz.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcppzd.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgcz.lib
    ${DDS_LIBRARY_DIRS}/rticonnextmsgczd.lib
    ${DDS_LIBRARY_DIRS}/rtiddsconnectorlua.lib
    ${DDS_LIBRARY_DIRS}/rtiddsconnectorluaz.lib
    ${DDS_LIBRARY_DIRS}/rtidlc.lib
    ${DDS_LIBRARY_DIRS}/rtidlcd.lib
    ${DDS_LIBRARY_DIRS}/rtidlcpp.lib
    ${DDS_LIBRARY_DIRS}/rtidlcpp2z.lib
    ${DDS_LIBRARY_DIRS}/rtidlcpp2zd.lib
    ${DDS_LIBRARY_DIRS}/rtidlcppd.lib
    ${DDS_LIBRARY_DIRS}/rtidlcppz.lib
    ${DDS_LIBRARY_DIRS}/rtidlcppzd.lib
    ${DDS_LIBRARY_DIRS}/rtidlcz.lib
    ${DDS_LIBRARY_DIRS}/rtidlczd.lib
    ${DDS_LIBRARY_DIRS}/rtijniroutingservice.lib
    ${DDS_LIBRARY_DIRS}/rtijniroutingserviced.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoring.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoring2.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoring2d.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoring2z.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoring2zd.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoringd.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoringz.lib
    ${DDS_LIBRARY_DIRS}/rtimonitoringzd.lib
    ${DDS_LIBRARY_DIRS}/rtipersistenceservice.lib
    ${DDS_LIBRARY_DIRS}/rtipersistenceserviced.lib
    ${DDS_LIBRARY_DIRS}/rtipersistenceservicez.lib
    ${DDS_LIBRARY_DIRS}/rtipersistenceservicezd.lib
    ${DDS_LIBRARY_DIRS}/rtirecordingservicecore.lib
    ${DDS_LIBRARY_DIRS}/rtirecordingservicecored.lib
    ${DDS_LIBRARY_DIRS}/rtirecordingservicecorez.lib
    ${DDS_LIBRARY_DIRS}/rtirecordingservicecorezd.lib
    ${DDS_LIBRARY_DIRS}/rtiroutingservice.lib
    ${DDS_LIBRARY_DIRS}/rtiroutingserviced.lib
    ${DDS_LIBRARY_DIRS}/rtiroutingservicez.lib
    ${DDS_LIBRARY_DIRS}/rtiroutingservicezd.lib
    ${DDS_LIBRARY_DIRS}/rtirsassigntransf.lib
    ${DDS_LIBRARY_DIRS}/rtirsassigntransfd.lib
    ${DDS_LIBRARY_DIRS}/rtirsinfrastructure.lib
    ${DDS_LIBRARY_DIRS}/rtirsinfrastructured.lib
    ${DDS_LIBRARY_DIRS}/rtirsinfrastructurez.lib
    ${DDS_LIBRARY_DIRS}/rtirsinfrastructurezd.lib
    ${DDS_LIBRARY_DIRS}/rtirsjniadapter.lib
    ${DDS_LIBRARY_DIRS}/rtirsjniadapterd.lib
    ${DDS_LIBRARY_DIRS}/rtiserviceadmincpp.lib
    ${DDS_LIBRARY_DIRS}/rtiserviceadmincppd.lib
    ${DDS_LIBRARY_DIRS}/rtiserviceadmincppz.lib
    ${DDS_LIBRARY_DIRS}/rtiserviceadmincppzd.lib
    ${DDS_LIBRARY_DIRS}/rtisqlite.lib
    ${DDS_LIBRARY_DIRS}/rtisqlited.lib
    ${DDS_LIBRARY_DIRS}/rtisqlitez.lib
    ${DDS_LIBRARY_DIRS}/rtisqlitezd.lib
    ${DDS_LIBRARY_DIRS}/rtistorageutils.lib
    ${DDS_LIBRARY_DIRS}/rtistorageutilsd.lib
    ${DDS_LIBRARY_DIRS}/rtistorageutilsz.lib
    ${DDS_LIBRARY_DIRS}/rtistorageutilszd.lib
    ${DDS_LIBRARY_DIRS}/rtitest.lib
    ${DDS_LIBRARY_DIRS}/rtitestd.lib
    ${DDS_LIBRARY_DIRS}/rtitestz.lib
    ${DDS_LIBRARY_DIRS}/rtitestzd.lib
    ${DDS_LIBRARY_DIRS}/rtiwebintegrationservice.lib
    ${DDS_LIBRARY_DIRS}/rtiwebintegrationserviced.lib
    ${DDS_LIBRARY_DIRS}/rtiwebintegrationservicez.lib
    ${DDS_LIBRARY_DIRS}/rtiwebintegrationservicezd.lib
    ${DDS_LIBRARY_DIRS}/rtixml2.lib
    ${DDS_LIBRARY_DIRS}/rtixml2d.lib
    ${DDS_LIBRARY_DIRS}/rtixml2z.lib
)
